### ISSUE TITLE
Render features as they're calculated 

### ISSUE THREAD

**Issue by LucasThompson** [piper-audio/ugly-duckling#19]
Rendering features as they're calculated, a la Sonic Visualiser, might be nice - if not just because it provides meaningful feedback to the user. 

Some limitations as it stands:
- The "higher level" extraction model I have in place at the moment - all features are returned at the end 
- Unsure whether waves-ui could support the backing datum changing over time. Would it just work?

**Comment by cannam** [comment]
> Would it just work?

No, not as things stand, at least not for matrix shapes (others may vary). Matrix caches its data into images once, between render and update phases.

**Comment by LucasThompson** [comment]
Perhaps an argument for extracting the cache stuff? i.e. the backing data for a layer is itself a cache, the layer would be constructed with a cache object for the data property

**Comment by cannam** [comment]
Only the shape knows what sort of cache it needs.

**Comment by LucasThompson** [comment]
This is mainly an upstream dependency issue: piper-audio/piper-js#3

**Comment by LucasThompson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Streaming features](https://trello.com/c/YMKp43yq/71-streaming-features)

**Comment by LucasThompson** [comment]
For later reference: It seems posting a message from the worker for each feature block swamps the event queue, and results in the overall extraction taking significantly longer. I may have missed something and it is actually something else, but that is my current understanding.

For now, I throttle the messages, sending one with the features so far when `(blocks to process / total blocks to process) * 100` increases by one, ultimately to update the progress bar.
