### ISSUE TITLE
All the annotations are red

### ISSUE THREAD

**Issue by cannam** [piper-audio/ugly-duckling#21]
There is some code in (ahem) waveform.component.ts that I think is supposed to pick a new colour for each annotation layer, but it doesn't seem to be working any more. All of the annotations and their cursors and highlight layers are coming out red.

**Comment by LucasThompson** [comment]
I realised the same thing last night actually. 

The component should probably take a colour as an input and the parent component decides.

There's a lot of logic hanging around in that class from when we were overlaying the features etc.

**Comment by cannam** [comment]
I bodged it in cannam/master for now.
