### ISSUE TITLE
In Chrome on Android, wrong volume control is used

### ISSUE THREAD

**Issue by cannam** [piper-audio/ugly-duckling#27]
(This might be unfixable by us, I dunno)

When I load the webapp in Chrome on Android and play audio, it plays using the "In-call volume" volume control rather than the media volume control. This means it doesn't follow the last volume setting I had for music, it only accepts a smaller set of possible volume settings (the in-call volume control is quite coarse), it doesn't appear to be possible to mute it at all, and if I turn the volume down, my next phone call is too quiet.

**Comment by cannam** [comment]
Looks like this problem https://bugs.chromium.org/p/chromium/issues/detail?id=311599, but that's from 2014 and marked as fixed in Chrome 35. (I'm using Chrome 58 beta but the current stable does the same thing.)

I wonder if it could be related to having the microphone open?

**Comment by LucasThompson** [comment]
The audio is being played using an `<audio>` tag, so I would expect the browser to do something sensible with that. 

Worth looking into RE the microphone thing. 

Does your phone work properly on other websites, YouTube for example?

**Comment by cannam** [comment]
Yes it does, although I confused myself for a moment when trying to check this just now - I started Youtube and played a video and it came through the in-call volume control - but Chrome was still running with the Ugly Duckling tab open. Close that, and everything else (including Ugly Duckling in Firefox) plays through the correct media volume control.

**Comment by LucasThompson** [comment]
Is this solved after merging #35 ?
