### ISSUE TITLE
Incorporate styling into an angular material theme

### ISSUE THREAD

**Issue by LucasThompson** [piper-audio/ugly-duckling#28]
The change to the colour app bar clashes with the other material components, i.e. the buttons and the select component in the extraction menu. 

Typically the primary colour in the material theme is used for all those elements.

There is a  [guide](https://material.angular.io/guide/theming) in the angular material docs for defining a custom theme, seems arduous.

**Comment by cannam** [comment]
Blimey, that guide. How I despise the web these days. Well, and back then too.

At this point, a theme identical to the one we are using (the blue Material theme) but with the material version of blue changed to #0868ac globally would seem like a reasonable compromise. It would make things consistent, would give us a slightly different overall colour from the default (http://web.archive.org/web/20050209070147fw_/http://media.k10k.net:80/issues/issue024/lesson1.htm) which is always encouraging, and I guess would prepare the ground a bit for any further styling we wanted to do.

**Comment by cannam** [comment]
Tested your change, looks nice. To deploy it, do I just need the usual dist/gh-pages .js and .css files or has anything else changed? (I guess I can just try it)

**Comment by LucasThompson** [comment]
Try and all will be revealed! (yes, to the first part)
